const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const source = fs.readFileSync("ios/HablaEcuador/NativeSpeech.js", "utf8");
function harness(origin = "https://mathewdmoore.github.io", path = "/habla-ecuador/translator.html") {
  const messages = [];
  const window = {webkit:{messageHandlers:{hablaSpeech:{postMessage:message => messages.push(structuredClone(message))}}}};
  vm.runInNewContext(source, {window, location:{origin, pathname:path}, EventTarget, Event, DOMException});
  return {window, messages};
}
assert.equal(harness("https://example.com").window.SpeechRecognition, undefined);
assert.equal(harness(undefined, "/unrelated/").window.SpeechRecognition, undefined);
const {window, messages} = harness();
const receive = window.__hablaNativeSpeech;
const recognition = new window.SpeechRecognition();
const events = [];
recognition.lang = "es-EC";
recognition.interimResults = true;
recognition.continuous = true;
recognition.onstart = () => events.push("start");
recognition.onresult = event => events.push([event.results[0][0].transcript, event.results[0].isFinal]);
recognition.onerror = event => events.push(event.error);
recognition.onend = () => events.push("end");
recognition.start();
assert.deepEqual(messages[0], {action:"start", id:"1", lang:"es-EC", interimResults:true, continuous:true});
assert.throws(() => recognition.start(), {name:"InvalidStateError"});
receive({id:"1", type:"start"});
receive({id:"1", type:"result", text:"hola", final:false});
receive({id:"1", type:"result", text:"hola de nuevo", final:true});
recognition.stop();
assert.deepEqual(messages.at(-1), {action:"stop", id:"1"});
receive({id:"1", type:"end"});
receive({id:"1", type:"result", text:"stale", final:true});
receive({id:"1", type:"end"});
assert.deepEqual(events, ["start", ["hola", false], ["hola de nuevo", true], "end"]);
recognition.start();
recognition.abort();
assert.deepEqual(messages.at(-1), {action:"abort", id:"2"});
receive({id:"2", type:"error", error:"aborted"});
receive({id:"2", type:"end"});
assert.deepEqual(events.slice(-2), ["aborted", "end"]);
const finalOnly = new window.webkitSpeechRecognition();
let results = 0;
let listenerEnds = 0;
finalOnly.onresult = () => results++;
finalOnly.addEventListener("end", () => listenerEnds++);
finalOnly.start();
receive({id:"3", type:"result", text:"partial", final:false});
receive({id:"3", type:"result", text:"complete", final:true});
receive({id:"3", type:"error", error:"not-allowed"});
receive({id:"3", type:"end"});
assert.equal(results, 1);
assert.equal(listenerEnds, 1);
// Full-song restart can start a new instance from onend without retaining stale ownership.
const restart = new window.SpeechRecognition();
restart.onend = () => restart.start();
restart.start();
receive({id:"4", type:"end"});
assert.equal(messages.at(-1).id, "5");
receive({id:"4", type:"end"});
assert.equal(messages.at(-1).id, "5");
// A failed transport must release the instance so a later retry can start.
const failed = new window.SpeechRecognition();
const transport = window.webkit.messageHandlers.hablaSpeech;
const postMessage = transport.postMessage;
transport.postMessage = () => { throw new Error("Unavailable"); };
assert.throws(() => failed.start(), /Unavailable/);
transport.postMessage = postMessage;
assert.doesNotThrow(() => failed.start());
console.log("Native speech bridge: passed (JavaScript behavior; no physical iPhone audio test)");
