var transcript = NativeTranscript()
transcript.update(text: "hola", start: 0, end: 1, final: false)
assert(transcript.text == "hola")
transcript.update(text: "hola María", start: 0, end: 2, final: false)
assert(transcript.text == "hola María", "An interim revision must replace, not append")
transcript.update(text: "Hola, María.", start: 0, end: 2, final: true)
transcript.update(text: "Hola, María.", start: 0, end: 2, final: true)
assert(transcript.text == "Hola, María.", "Duplicate final delivery must not duplicate words")
transcript.update(text: "Hola, María.", start: 3, end: 5, final: true)
assert(transcript.text == "Hola, María. Hola, María.", "Repeated chorus at a later time must survive")
transcript.update(text: "stale", start: 1, end: 2, final: false)
assert(!transcript.text.contains("stale"), "An old callback cannot overwrite finalized text")
transcript.update(text: "adiós", start: 6, end: 7, final: false)
transcript.update(text: "adiós a todos", start: 6.2, end: 8, final: true)
assert(transcript.text.hasSuffix("adiós a todos"), "Overlapping volatile ranges must be replaced")
transcript.update(text: "bad", start: .nan, end: 20, final: true)
transcript.update(text: "bad", start: 21, end: 20, final: true)
assert(!transcript.text.contains("bad"))
var revisions = NativeTranscript()
revisions.update(text: "uno", start: 0, end: 1, final: false)
revisions.update(text: "dos", start: 1, end: 2, final: false)
revisions.update(text: "uno y dos", start: 0, end: 2, final: true)
assert(revisions.text == "uno y dos", "A merged final range must replace both volatile passages")
revisions.update(text: "interim", start: 3, end: 4, final: false)
revisions.update(text: "", start: 3, end: 4, final: true)
assert(revisions.text == "uno y dos", "An empty revision must clear its volatile range")
var fresh = NativeTranscript()
assert(fresh.text.isEmpty, "A new session must not inherit a previous song")
print("Native transcript state: passed")
