const assert=require('node:assert/strict');
const helper=require('../screenshot-import.js');
const file={type:'image/png',size:300,name:'test.png'};
async function main(){
 assert.deepEqual(helper.cropBounds(946,2048,{top:14,bottom:74}),{x:0,y:286,width:946,height:1230});
 assert.deepEqual(helper.cropBounds(100,100,{top:-10,bottom:150}),{x:0,y:0,width:100,height:100});
 assert.ok(helper.cropBounds(100,100,{top:70,bottom:20}).height>=1,'crop cannot collapse');
 const solid=new Uint8ClampedArray([180,80,70,255,180,80,70,255,180,80,70,255,255,255,255,255,210,135,128,255]);
 assert.equal(helper.improveContrast(solid),true);
 assert.deepEqual(Array.from(solid.slice(0,4)),[255,255,255,255]);
 assert.deepEqual(Array.from(solid.slice(16,20)),[0,0,0,255],'faded light text on colour remains foreground');
 const varied=new Uint8ClampedArray([0,0,0,255,50,100,200,255,255,255,255,255]);const original=Array.from(varied);
 assert.equal(helper.improveContrast(varied),false);assert.deepEqual(Array.from(varied),original,'mixed backgrounds are not thresholded');
 assert.equal(helper.validate(file),file);
 assert.throws(()=>helper.validate({type:'image/heic',size:1}),/HEIC/);
 assert.throws(()=>helper.validate({type:'image/png',size:11*1024*1024}),/10 MB/);
 const imageItem={kind:'file',type:'image/png',getAsFile:()=>file};
 assert.equal(helper.imageFromClipboard({items:[imageItem]}),file);
 assert.equal(helper.imageFromClipboard({items:[{kind:'string',type:'text/plain'}]}),null);
 assert.equal(helper.imageFromClipboard({files:[file]}),file);
 let terminated=0,calls=0;
 const worker={recognize:async image=>{assert.equal(image,file,'original image only goes to local worker');return {data:{text:'El agua está limpia.\r\n\r\nSegunda línea.',confidence:95}};},terminate:async()=>{terminated++;}};
 const reader={createWorker:async(language,mode,options)=>{calls++;assert.equal(language,'spa');assert.equal(mode,1);assert.match(options.workerPath,/6\.0\.1/);return worker;}};
 const extracted=await helper.extract(file,{reader});assert.equal(extracted.text,'El agua está limpia.\n\nSegunda línea.');assert.equal(terminated,1);
 let current=true;reader.createWorker=async()=>{current=false;return worker;};
 assert.equal(await helper.extract(file,{reader,isCurrent:()=>current}),null);assert.equal(terminated,2,'superseded startup still releases worker');
 reader.createWorker=async()=>worker;worker.recognize=async()=>({data:{text:''}});
 await assert.rejects(helper.extract(file,{reader}),/No readable/);assert.equal(terminated,3);
 worker.recognize=async()=>{throw new Error('bad image');};
 await assert.rejects(helper.extract(file,{reader}),/bad image/);assert.equal(terminated,4);
 const controller=new AbortController();let started;
 const recognitionStarted=new Promise(resolve=>{started=resolve;});
 worker.recognize=()=>{started();return new Promise(()=>{});};
 const cancelled=helper.extract(file,{reader,signal:controller.signal});
 await recognitionStarted;controller.abort();
 await assert.rejects(cancelled,/cancelled/);assert.equal(terminated,5,'cancel must settle even if worker never responds');
 worker.recognize=async()=>({data:{text:'Nuevo texto.'}});
 assert.equal((await helper.extract(file,{reader})).text,'Nuevo texto.','a new import works after cancellation');
 let finishStartup;reader.createWorker=()=>new Promise(resolve=>{finishStartup=resolve;});
 const startupController=new AbortController();
 const startupCancelled=helper.extract(file,{reader,signal:startupController.signal});
 startupController.abort();await assert.rejects(startupCancelled,/cancelled/);
 finishStartup(worker);await Promise.resolve();assert.equal(terminated,7,'late startup after cancellation releases worker');
 console.log('Screenshot checks passed: file/clipboard validation, local-worker routing, paragraph fidelity, stale results, cancellation settlement and worker release.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
