const assert=require('node:assert/strict');
const {analyse,refine,workSense,prepare,residue,slang}=require('../spanish-context.js');
const usage=(text,source='es-EC',target='en-GB')=>slang(text,{source,target});
assert.equal(prepare('Ese huerco viene.',{source:'es-MX'}),'Ese niño viene.');
assert.equal(prepare('Las huercas vienen.',{source:'es-MX'}),'Las niñas vienen.');
for(const text of ['El restaurante Huerco.','El Huerco viene.','"Ese huerco viene."','El huerco es un demonio.'])assert.equal(prepare(text,{source:'es-MX'}),text);
assert.equal(prepare('Ese huerco viene.',{source:'es-EC'}),'Ese huerco viene.');
assert.equal(prepare('Ese huerco viene.',{source:'es-MX',purpose:'academic'}),'Ese huerco viene.');
assert.equal(residue('¡No mames!','Do not suck!',{region:'es-MX'})[0].kind,'slang-literal');
assert.equal(residue('¡No mames!','No fucking way!',{region:'es-MX'}).length,0);
assert.equal(residue('No mames leche.','Do not suck milk.',{region:'es-MX'}).length,0);
assert.equal(residue('No mames.','Do not suck.',{region:'es-EC'}).length,0);
assert.match(usage('Ese huerco viene.','es-MX')[0].detail,/Monterrey/);
assert.equal(usage('Huerco','es-VE').length,0,'country clues do not silently become universal');
assert.equal(usage('huercote','es-MX').length,0,'whole words only');
assert.equal(usage('égüeyé','es-MX').length,0,'Unicode word boundaries');
assert.match(usage('¡No mames, güey!','es-MX','en-US')[1].detail,/U.S. options/);
assert.equal(usage('¡No mames, güey!','es-MX').length,2);
assert.match(usage('Wey','es-MX')[0].detail,/mate/);
assert.equal(usage('¡Coño de su madre!','es-VE').length,1,'long expressions do not duplicate nested notes');
assert.equal(usage('¡Coño de su madre! Otro coño.','es-VE').length,2,'independent later words remain recognized');
assert.equal(usage('Un cono de helado.','es-EC').length,0,'ñ is not n');
assert.match(usage('La chama vino con su pana.','es-VE')[0].detail,/Caracas-specific review pending/);
assert.match(usage('Mi pata llega.','es-PE')[0].detail,/Lima-specific/);
assert.match(usage('Mi pata llega.','es-EC')[0].detail,/group of friends/);
assert.match(usage('Es huevón.','es-MX')[0].detail,/lazy person/);
assert.match(usage('Es huevón.','es-PE')[0].detail,/idiot/);
assert.equal(usage('Ni huevón.','es-PE').length,1,'refusal gets the phrase reading');
assert.match(usage('Parce, esa gonorrea.','es-CO')[1].detail,/Bogotá/);
assert.match(usage('La prueba de gonorrea.','es-CO','en-US')[0].detail,/Medical context: gonorrhea/);
assert.doesNotMatch(usage('La prueba de gonorrea.','es-CO')[0].detail,/Offensive insult/);
assert.match(usage('¡Pucha!','es-BO')[0].detail,/Mild euphemistic/);
assert.match(usage('¡Puta!','es-BO')[0].detail,/Vulgar/);
assert.match(usage('¡Chuta!')[0].detail,/Mild informal/);
assert.equal(slang('No mames.',{source:'es-MX',purpose:'academic'}).length,0);
assert.equal(slang('No mames.',{source:'en-US'}).length,0);
assert.equal(usage('"No mames."','es-MX').length,1,'notes can explain quoted speech without rewriting it');
assert.equal(prepare('¡No mames, güey!'),'¡No mames, güey!','recognition never sanitizes or rewrites profanity');
assert.equal(refine('My buddy.','Mi pata.').text,'My buddy.','no automatic ambiguity resolution');
assert.equal(prepare('Mis cajas de cartón chiquitas.'),'Mis cajas de cartón pequeñas.');
assert.equal(prepare('Los vasos son chiquitos.'),'Los vasos son pequeños.');
assert.equal(prepare('El restaurante Chiquito tiene mesas.'),'El restaurante Chiquito tiene mesas.');
assert.equal(prepare('La casa de Chiquito.'),'La casa de Chiquito.');
assert.equal(prepare('"Las cajas chiquitas."'),'"Las cajas chiquitas."');
assert.equal(prepare('Las cajas chiquitas.',{purpose:'academic'}),'Las cajas chiquitas.');
assert.equal(residue('Las cajas chiquitas.','Chiquitas boxes.').length,1);
assert.equal(residue('Las cajas chiquitas.','Small boxes.').length,0);
assert.equal(residue('La salsa es cumbia.','The salsa is cumbia.').length,0);
assert.equal(residue('El restaurante Chiquito.','The Chiquito restaurant.').length,0);
assert.equal(residue('Las cajas chiquitas.','"Chiquitas" boxes.').length,0);
assert.equal(residue('Las cajas chiquitas.','Chiquitas boxes.',{purpose:'academic'}).length,0);
assert.equal(refine('Come, heart, listen.','Ven, corazón, escucha.').text,'Come, sweetheart, listen.');
assert.equal(refine('The heart is an organ.','El corazón es un órgano.').text,'The heart is an organ.');
assert.equal(refine('Come, heart, listen.','Ven, corazón, escucha.',{purpose:'academic'}).text,'Come, heart, listen.');
assert.equal(refine('"Come, heart, listen."','"Ven, corazón, escucha."').text,'"Come, heart, listen."');
assert.equal(refine('A kiss (how rich).','Un beso (qué rico).').text,'A kiss (that feels so good).');
assert.equal(refine('The soup (how rich).','La sopa (qué rico).').text,'The soup (how rich).');
assert.equal(refine('A kiss and chocolate (how rich).','Un beso y chocolate (qué rico).').text,'A kiss and chocolate (how rich).');
assert.equal(refine('No hugs (how rich).','No hay abrazos (qué rico).').text,'No hugs (how rich).');
assert.equal(refine('A kiss (how nice).','Un beso (qué rico).').text,'A kiss (how nice).','acceptable pleasure wording is retained');
assert.equal(refine('"A kiss (how rich)."','Un beso (qué rico).').text,'"A kiss (how rich)."');
assert.equal(refine('I want you.','Te quiero.').text,'I want you.','ambiguous wanting versus affection stays editable');
assert.equal(refine('Wait, heart, wait that it is late.','Espera, corazón, espera que ya es tarde.').text,'Wait, sweetheart, wait because it is late.');
assert.equal(refine('The dance that I love.','El baile que me encanta.').text,'The dance that I love.','relative clauses stay unchanged');
assert.equal(refine('"Wait, heart, wait that it is late."','Espera, corazón, espera que ya es tarde.').text,'"Wait, heart, wait that it is late."');
assert.equal(refine('Wait, heart, "wait that it is late."','Espera, corazón, espera que ya es tarde.').text,'Wait, sweetheart, "wait that it is late."','earlier edits do not shift quote protection');
for(const source of ['es-EC','es-BO','es-MX','es-VE','es-PE','es-CO']) {
 const notes=analyse('Ven, corazón, escucha. Te quiero.',{source});
 assert.equal(notes.length,2);assert.match(notes[0].detail,/does not identify a country/);
 assert.equal(analyse('guagua',{source})[0].term,'guagua');
 assert.match(analyse('Qué chévere.',{source})[0].detail,/does not identify a city or country/);
}
assert.equal(analyse('ñaño',{source:'es-BO'})[0].term,'ñaño / ñaña');
assert.equal(analyse('Ven, corazón, escucha.',{purpose:'academic'}).length,0);
assert.equal(analyse('Ven, corazón, escucha.',{source:'en-US'}).length,0);
assert.equal(analyse('Una oración entre',{image:true}).at(-1).term,'Incomplete ending');
assert.equal(analyse('Una oración entre',{image:false}).length,0);
assert.equal(workSense('Ya voy al camello.'),true);
assert.equal(workSense('El camello tiene una joroba.'),false);
assert.equal(workSense('El camello de la zapatería.'),false);
assert.equal(workSense('El camello es grande.'),false);
console.log('Spanish context checks passed: affection, pleasure, ambiguity, regional clues, research/quote protection and incomplete images.');
